name: Run
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python3 -c 
          import requests
           import time
            import uuid
             import random

VIDEO_ID = 'cf89b1de7a3db4d79069629e96116ebb'for i in range(10):
                cid = str(random.randint(1000000000000, 9999999999999))
    params = {
        'event_name': 'play_start',
        'event_action': 'PL',
        'cid': cid,
        'session_id': f'{cid}_{int(time.time()*1000)}',
        'user_id': random.randint(10000000, 99999999),
        'content_id': VIDEO_ID,
    }
    try:
        r = requests.get('https://goya.rutube.ru/v2/online', params=params, timeout=10)
        print(f'{i+1}/10: {r.status_code}')
    except Exception as e:
        print(f'{i+1}/10: Ошибка {e}')
    time.sleep(30)

print('Готово!')
"
