name: Run Rutube Bot

on:
  schedule:
    - cron: '0 */6 * * *'   # Каждые 6 часов
  workflow_dispatch:         # Для ручного запуска

jobs:
  rutube-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          google-chrome --version
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run bot
        run: python bot.py
