name: Free VPS

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Install tmate
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate
          
      - name: Start SSH
        run: |
          echo "=== ПОДКЛЮЧАЙСЯ ПО SSH ==="
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "Команда для подключения:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "============================"
          sleep 6h
